env = "test" # "test", "dev", "prod"

[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

[server]
# The address to bind to.
port = 8080
# cert file path to enable https, example: "/etc/https/mydomain.crt"
cert_file = ""
# key file path to enable https, example: "/etc/https/mydomain.key"
key_file = ""
# The maximum number of seconds to wait for graceful shutdown.
graceful_shutdown = 60

[scylla]
# Scylla server nodes
nodes = ["127.0.0.1:9042"]
# Scylla server username
username = ""
# Scylla server password
password = ""

[qdrant]
url = "http://127.0.0.1:6334"
api_key = ""

[redis]
# Redis server address
host = "127.0.0.1"
# Redis server port
port = 6379
# Redis server username
username = ""
# Redis server password
password = ""
# The maximum number of connections managed by the pool, should > 0.
max_connections = 10

[ai.agent]
client_pem_file = ""
client_root_cert_file = ""

[ai.openai]
agent_endpoint = ""
api_key = ""
org_id = ""

[[ai.azureais]]
agent_endpoint = ""
resource_name = "yiwen"
api_key = ""
api_version = "2023-05-15"
chat_model = "gpt-35-turbo"
embedding_model = "embedding-ada-002"
gpt4_chat_model = "gpt-4"


[[ai.azureais]]
agent_endpoint = "https://jarvis-us.yiwen.vpc:8443"
resource_name = "yw-au-ea"
api_key = "6fe6bcb6c7044fea9dcba5ff141fe1f1"
api_version = "2023-05-15"
embedding_model = "text-embedding"
chat_model = "gpt-35-turbo"
gpt4_chat_model = "gpt-4"
