name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-bookworm
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
      scylladb1:
        image: scylladb/scylla:5.2
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run clippy
        run: cargo clippy --verbose --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose --workspace -- --nocapture
